// typesCaliper.h
// This file is generated by Shroud 0.11.0. Do not edit.
// For C users and C++ implementation

#ifndef TYPESCALIPER_H
#define TYPESCALIPER_H

#include <stddef.h>


#ifdef __cplusplus
extern "C" {
#endif

// helper capsule_data_helper
struct s_cali_SHROUD_capsule_data {
    void *addr;     /* address of C++ memory */
    int idtor;      /* index of destructor */
};
typedef struct s_cali_SHROUD_capsule_data cali_SHROUD_capsule_data;

// helper array_context
struct s_cali_SHROUD_array {
    cali_SHROUD_capsule_data cxx;      /* address of C++ memory */
    union {
        const void * base;
        const char * ccharp;
    } addr;
    int type;        /* type of element */
    size_t elem_len; /* bytes-per-item or character len in c++ */
    size_t size;     /* size of data in c++ */
    int rank;        /* number of dimensions */
};
typedef struct s_cali_SHROUD_array cali_SHROUD_array;

// helper capsule_cali_Annotation
struct s_cali_Annotation {
    void *addr;     /* address of C++ memory */
    int idtor;      /* index of destructor */
};
typedef struct s_cali_Annotation cali_Annotation;

// helper capsule_cali_BufferedRegionProfile
struct s_cali_BufferedRegionProfile {
    void *addr;     /* address of C++ memory */
    int idtor;      /* index of destructor */
};
typedef struct s_cali_BufferedRegionProfile cali_BufferedRegionProfile;

// helper capsule_cali_ConfigManager
struct s_cali_ConfigManager {
    void *addr;     /* address of C++ memory */
    int idtor;      /* index of destructor */
};
typedef struct s_cali_ConfigManager cali_ConfigManager;

// helper capsule_cali_ScopeAnnotation
struct s_cali_ScopeAnnotation {
    void *addr;     /* address of C++ memory */
    int idtor;      /* index of destructor */
};
typedef struct s_cali_ScopeAnnotation cali_ScopeAnnotation;

void cali_SHROUD_memory_destructor(cali_SHROUD_capsule_data *cap);

#ifdef __cplusplus
}
#endif

#endif  // TYPESCALIPER_H
