! wrapfcaliper.f
! This file is generated by Shroud 0.11.0. Do not edit.
!>
!! \file wrapfcaliper.f
!! \brief Shroud generated wrapper for cali namespace
!<
! splicer begin file_top
! splicer end file_top
module caliper_mod
    use iso_c_binding, only : C_INT, C_NULL_PTR, C_PTR, C_SIZE_T
    ! splicer begin module_use
    ! splicer end module_use
    implicit none

    ! splicer begin module_top
    ! splicer end module_top

    ! helper capsule_data_helper
    type, bind(C) :: SHROUD_capsule_data
        type(C_PTR) :: addr = C_NULL_PTR  ! address of C++ memory
        integer(C_INT) :: idtor = 0       ! index of destructor
    end type SHROUD_capsule_data

    ! helper array_context
    type, bind(C) :: SHROUD_array
        ! address of C++ memory
        type(SHROUD_capsule_data) :: cxx
        ! address of data in cxx
        type(C_PTR) :: base_addr = C_NULL_PTR
        ! type of element
        integer(C_INT) :: type
        ! bytes-per-item or character len of data in cxx
        integer(C_SIZE_T) :: elem_len = 0_C_SIZE_T
        ! size of data in cxx
        integer(C_SIZE_T) :: size = 0_C_SIZE_T
        ! number of dimensions
        integer(C_INT) :: rank = -1
    end type SHROUD_array

    type, bind(C) :: SHROUD_scopeannotation_capsule
        type(C_PTR) :: addr = C_NULL_PTR  ! address of C++ memory
        integer(C_INT) :: idtor = 0       ! index of destructor
    end type SHROUD_scopeannotation_capsule

    type scopeannotation
        type(SHROUD_scopeannotation_capsule) :: cxxmem
        ! splicer begin class.ScopeAnnotation.component_part
        ! splicer end class.ScopeAnnotation.component_part
    contains
        procedure :: end => scopeannotation_end
        procedure :: get_instance => scopeannotation_get_instance
        procedure :: set_instance => scopeannotation_set_instance
        procedure :: associated => scopeannotation_associated
        ! splicer begin class.ScopeAnnotation.type_bound_procedure_part
        ! splicer end class.ScopeAnnotation.type_bound_procedure_part
    end type scopeannotation

    type, bind(C) :: SHROUD_configmanager_capsule
        type(C_PTR) :: addr = C_NULL_PTR  ! address of C++ memory
        integer(C_INT) :: idtor = 0       ! index of destructor
    end type SHROUD_configmanager_capsule

    type configmanager
        type(SHROUD_configmanager_capsule) :: cxxmem
        ! splicer begin class.ConfigManager.component_part
        ! splicer end class.ConfigManager.component_part
    contains
        procedure :: delete => configmanager_delete
        procedure :: add => configmanager_add
        procedure :: error => configmanager_error
        procedure :: error_msg => configmanager_error_msg
        procedure :: start => configmanager_start
        procedure :: stop => configmanager_stop
        procedure :: flush => configmanager_flush
        procedure :: get_instance => configmanager_get_instance
        procedure :: set_instance => configmanager_set_instance
        procedure :: associated => configmanager_associated
        ! splicer begin class.ConfigManager.type_bound_procedure_part
        ! splicer end class.ConfigManager.type_bound_procedure_part
    end type configmanager

    interface operator (.eq.)
        module procedure scopeannotation_eq
        module procedure configmanager_eq
    end interface

    interface operator (.ne.)
        module procedure scopeannotation_ne
        module procedure configmanager_ne
    end interface

    interface

        function c_scopeannotation_begin(name, SHT_crv) &
                result(SHT_rv) &
                bind(C, name="cali_ScopeAnnotation_begin")
            use iso_c_binding, only : C_CHAR, C_PTR
            import :: SHROUD_scopeannotation_capsule
            implicit none
            character(kind=C_CHAR), intent(IN) :: name(*)
            type(SHROUD_scopeannotation_capsule), intent(OUT) :: SHT_crv
            type(C_PTR) SHT_rv
        end function c_scopeannotation_begin

        subroutine c_scopeannotation_end(self) &
                bind(C, name="cali_ScopeAnnotation_end")
            import :: SHROUD_scopeannotation_capsule
            implicit none
            type(SHROUD_scopeannotation_capsule), intent(IN) :: self
        end subroutine c_scopeannotation_end

        ! splicer begin class.ScopeAnnotation.additional_interfaces
        ! splicer end class.ScopeAnnotation.additional_interfaces

        function c_configmanager_new(SHT_crv) &
                result(SHT_rv) &
                bind(C, name="cali_ConfigManager_new")
            use iso_c_binding, only : C_PTR
            import :: SHROUD_configmanager_capsule
            implicit none
            type(SHROUD_configmanager_capsule), intent(OUT) :: SHT_crv
            type(C_PTR) SHT_rv
        end function c_configmanager_new

        subroutine c_configmanager_delete(self) &
                bind(C, name="cali_ConfigManager_delete")
            import :: SHROUD_configmanager_capsule
            implicit none
            type(SHROUD_configmanager_capsule), intent(IN) :: self
        end subroutine c_configmanager_delete

        subroutine c_configmanager_add(self, config) &
                bind(C, name="cali_ConfigManager_add")
            use iso_c_binding, only : C_CHAR
            import :: SHROUD_configmanager_capsule
            implicit none
            type(SHROUD_configmanager_capsule), intent(IN) :: self
            character(kind=C_CHAR), intent(IN) :: config(*)
        end subroutine c_configmanager_add

        function c_configmanager_error(self) &
                result(SHT_rv) &
                bind(C, name="cali_ConfigManager_error")
            use iso_c_binding, only : C_BOOL
            import :: SHROUD_configmanager_capsule
            implicit none
            type(SHROUD_configmanager_capsule), intent(IN) :: self
            logical(C_BOOL) :: SHT_rv
        end function c_configmanager_error

        subroutine c_configmanager_error_msg_bufferify(self, DSHF_rv) &
                bind(C, name="cali_ConfigManager_error_msg_bufferify")
            import :: SHROUD_array, SHROUD_configmanager_capsule
            implicit none
            type(SHROUD_configmanager_capsule), intent(IN) :: self
            type(SHROUD_array), intent(OUT) :: DSHF_rv
        end subroutine c_configmanager_error_msg_bufferify

        subroutine c_configmanager_start(self) &
                bind(C, name="cali_ConfigManager_start")
            import :: SHROUD_configmanager_capsule
            implicit none
            type(SHROUD_configmanager_capsule), intent(IN) :: self
        end subroutine c_configmanager_start

        subroutine c_configmanager_stop(self) &
                bind(C, name="cali_ConfigManager_stop")
            import :: SHROUD_configmanager_capsule
            implicit none
            type(SHROUD_configmanager_capsule), intent(IN) :: self
        end subroutine c_configmanager_stop

        subroutine c_configmanager_flush(self) &
                bind(C, name="cali_ConfigManager_flush")
            import :: SHROUD_configmanager_capsule
            implicit none
            type(SHROUD_configmanager_capsule), intent(IN) :: self
        end subroutine c_configmanager_flush

        ! splicer begin class.ConfigManager.additional_interfaces
        ! splicer end class.ConfigManager.additional_interfaces

#ifdef CALIPER_HAVE_MPI
        subroutine cali_mpi_init() &
                bind(C, name="cali_mpi_init")
            implicit none
        end subroutine cali_mpi_init
#endif

        subroutine cali_init() &
                bind(C, name="cali_init")
            implicit none
        end subroutine cali_init

        subroutine c_cali_config_preset(key, value) &
                bind(C, name="cali_config_preset")
            use iso_c_binding, only : C_CHAR
            implicit none
            character(kind=C_CHAR), intent(IN) :: key(*)
            character(kind=C_CHAR), intent(IN) :: value(*)
        end subroutine c_cali_config_preset

        subroutine c_cali_config_set(key, value) &
                bind(C, name="cali_config_set")
            use iso_c_binding, only : C_CHAR
            implicit none
            character(kind=C_CHAR), intent(IN) :: key(*)
            character(kind=C_CHAR), intent(IN) :: value(*)
        end subroutine c_cali_config_set

        ! splicer begin additional_interfaces
        ! splicer end additional_interfaces
    end interface

    interface
        ! helper copy_string
        ! Copy the char* or std::string in context into c_var.
        subroutine SHROUD_copy_string_and_free(context, c_var, c_var_size) &
             bind(c,name="cali_ShroudCopyStringAndFree")
            use, intrinsic :: iso_c_binding, only : C_CHAR, C_SIZE_T
            import SHROUD_array
            type(SHROUD_array), intent(IN) :: context
            character(kind=C_CHAR), intent(OUT) :: c_var(*)
            integer(C_SIZE_T), value :: c_var_size
        end subroutine SHROUD_copy_string_and_free
    end interface

contains

    function scopeannotation_begin(name) &
            result(SHT_rv)
        use iso_c_binding, only : C_NULL_CHAR, C_PTR
        character(len=*), intent(IN) :: name
        type(scopeannotation) :: SHT_rv
        ! splicer begin class.ScopeAnnotation.method.begin
        type(C_PTR) :: SHT_prv
        SHT_prv = c_scopeannotation_begin(trim(name)//C_NULL_CHAR, &
            SHT_rv%cxxmem)
        ! splicer end class.ScopeAnnotation.method.begin
    end function scopeannotation_begin

    subroutine scopeannotation_end(obj)
        class(scopeannotation) :: obj
        ! splicer begin class.ScopeAnnotation.method.end
        call c_scopeannotation_end(obj%cxxmem)
        ! splicer end class.ScopeAnnotation.method.end
    end subroutine scopeannotation_end

    ! Return pointer to C++ memory.
    function scopeannotation_get_instance(obj) result (cxxptr)
        use iso_c_binding, only: C_PTR
        class(scopeannotation), intent(IN) :: obj
        type(C_PTR) :: cxxptr
        cxxptr = obj%cxxmem%addr
    end function scopeannotation_get_instance

    subroutine scopeannotation_set_instance(obj, cxxmem)
        use iso_c_binding, only: C_PTR
        class(scopeannotation), intent(INOUT) :: obj
        type(C_PTR), intent(IN) :: cxxmem
        obj%cxxmem%addr = cxxmem
        obj%cxxmem%idtor = 0
    end subroutine scopeannotation_set_instance

    function scopeannotation_associated(obj) result (rv)
        use iso_c_binding, only: c_associated
        class(scopeannotation), intent(IN) :: obj
        logical rv
        rv = c_associated(obj%cxxmem%addr)
    end function scopeannotation_associated

    ! splicer begin class.ScopeAnnotation.additional_functions
    ! splicer end class.ScopeAnnotation.additional_functions

    function configmanager_new() &
            result(SHT_rv)
        use iso_c_binding, only : C_PTR
        type(configmanager) :: SHT_rv
        ! splicer begin class.ConfigManager.method.new
        type(C_PTR) :: SHT_prv
        SHT_prv = c_configmanager_new(SHT_rv%cxxmem)
        ! splicer end class.ConfigManager.method.new
    end function configmanager_new

    subroutine configmanager_delete(obj)
        class(configmanager) :: obj
        ! splicer begin class.ConfigManager.method.delete
        call c_configmanager_delete(obj%cxxmem)
        ! splicer end class.ConfigManager.method.delete
    end subroutine configmanager_delete

    subroutine configmanager_add(obj, config)
        use iso_c_binding, only : C_NULL_CHAR
        class(configmanager) :: obj
        character(len=*), intent(IN) :: config
        ! splicer begin class.ConfigManager.method.add
        call c_configmanager_add(obj%cxxmem, trim(config)//C_NULL_CHAR)
        ! splicer end class.ConfigManager.method.add
    end subroutine configmanager_add

    function configmanager_error(obj) &
            result(SHT_rv)
        use iso_c_binding, only : C_BOOL
        class(configmanager) :: obj
        logical :: SHT_rv
        ! splicer begin class.ConfigManager.method.error
        SHT_rv = c_configmanager_error(obj%cxxmem)
        ! splicer end class.ConfigManager.method.error
    end function configmanager_error

    function configmanager_error_msg(obj) &
            result(SHT_rv)
        class(configmanager) :: obj
        type(SHROUD_array) :: DSHF_rv
        character(len=:), allocatable :: SHT_rv
        ! splicer begin class.ConfigManager.method.error_msg
        call c_configmanager_error_msg_bufferify(obj%cxxmem, DSHF_rv)
        allocate(character(len=DSHF_rv%elem_len):: SHT_rv)
        call SHROUD_copy_string_and_free(DSHF_rv, SHT_rv, DSHF_rv%elem_len)
        ! splicer end class.ConfigManager.method.error_msg
    end function configmanager_error_msg

    subroutine configmanager_start(obj)
        class(configmanager) :: obj
        ! splicer begin class.ConfigManager.method.start
        call c_configmanager_start(obj%cxxmem)
        ! splicer end class.ConfigManager.method.start
    end subroutine configmanager_start

    subroutine configmanager_stop(obj)
        class(configmanager) :: obj
        ! splicer begin class.ConfigManager.method.stop
        call c_configmanager_stop(obj%cxxmem)
        ! splicer end class.ConfigManager.method.stop
    end subroutine configmanager_stop

    subroutine configmanager_flush(obj)
        class(configmanager) :: obj
        ! splicer begin class.ConfigManager.method.flush
        call c_configmanager_flush(obj%cxxmem)
        ! splicer end class.ConfigManager.method.flush
    end subroutine configmanager_flush

    ! Return pointer to C++ memory.
    function configmanager_get_instance(obj) result (cxxptr)
        use iso_c_binding, only: C_PTR
        class(configmanager), intent(IN) :: obj
        type(C_PTR) :: cxxptr
        cxxptr = obj%cxxmem%addr
    end function configmanager_get_instance

    subroutine configmanager_set_instance(obj, cxxmem)
        use iso_c_binding, only: C_PTR
        class(configmanager), intent(INOUT) :: obj
        type(C_PTR), intent(IN) :: cxxmem
        obj%cxxmem%addr = cxxmem
        obj%cxxmem%idtor = 0
    end subroutine configmanager_set_instance

    function configmanager_associated(obj) result (rv)
        use iso_c_binding, only: c_associated
        class(configmanager), intent(IN) :: obj
        logical rv
        rv = c_associated(obj%cxxmem%addr)
    end function configmanager_associated

    ! splicer begin class.ConfigManager.additional_functions
    ! splicer end class.ConfigManager.additional_functions

    subroutine cali_config_preset(key, value)
        use iso_c_binding, only : C_NULL_CHAR
        character(len=*), intent(IN) :: key
        character(len=*), intent(IN) :: value
        ! splicer begin function.cali_config_preset
        call c_cali_config_preset(trim(key)//C_NULL_CHAR, &
            trim(value)//C_NULL_CHAR)
        ! splicer end function.cali_config_preset
    end subroutine cali_config_preset

    subroutine cali_config_set(key, value)
        use iso_c_binding, only : C_NULL_CHAR
        character(len=*), intent(IN) :: key
        character(len=*), intent(IN) :: value
        ! splicer begin function.cali_config_set
        call c_cali_config_set(trim(key)//C_NULL_CHAR, &
            trim(value)//C_NULL_CHAR)
        ! splicer end function.cali_config_set
    end subroutine cali_config_set

    ! splicer begin additional_functions
    ! splicer end additional_functions

    function scopeannotation_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(scopeannotation), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function scopeannotation_eq

    function scopeannotation_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(scopeannotation), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function scopeannotation_ne

    function configmanager_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(configmanager), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function configmanager_eq

    function configmanager_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(configmanager), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function configmanager_ne

end module caliper_mod
