#!/usr/bin/env python3
#
# Copyright (c) 2024, Lawrence Livermore National Security, LLC.
# See top-level LICENSE file for details.
#
# SPDX-License-Identifier: BSD-3-Clause

import os
import os.path
import sys

exe_file = os.path.realpath(os.path.expanduser(__file__))
cali_prefix = os.path.dirname(os.path.dirname(exe_file))
cali_lib_path = os.path.join(cali_prefix, "lib64", "caliper")
sys.path.insert(0, cali_lib_path)

from cali2traceevent import main

if __name__ == "__main__":
    sys.exit(main())
